CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS issues (
    id BIGINT PRIMARY KEY, -- GitHub's internal unique ID
    number INT NOT NULL, -- issue number shown in the URL e.g. #4821
    title TEXT NOT NULL, -- issue title
    body TEXT, -- full description written by the author
    state TEXT NOT NULL, -- 'open' or 'closed'
    labels TEXT[], -- array of label names e.g. ['bug', 'help wanted']
    created_at TIMESTAMPTZ, -- when the issue was opened
    closed_at TIMESTAMPTZ, -- when it was closed, NULL if still open
    url TEXT, -- link to the issue on GitHub
    embedding vector(768) -- 768-dim meaning vector, filled in by the embedder
);

CREATE INDEX IF NOT EXISTS issue_embedding ON issues USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- Everytime an update or insertion happens the tsvector is calculated based on the title
-- and body, we use STORED so that we store the vector rather then recompute on selection for 
-- fast retreivals
ALTER TABLE issues ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (
    to_tsvector('english', coalesce(title,'') || ' ' || coalesce(body,''))
  ) STORED;

-- A GIN index is made here which basically maps lexeme generated by search_vector
-- to TID (page, slot) which is basically a singular row, GIN would handle the
-- decomposition of search vectors being unrolled and each value has an instance,
-- we would provide the user query in this form:

-- SELECT * FROM issues WHERE search_vector @@ to_tsquery('memory & parser')
CREATE INDEX IF NOT EXISTS issues_search_gin ON issues USING gin (search_vector);